# WoW Ranged Weapons

In [13]:
import pandas as pd
from sqlalchemy import create_engine

In [14]:
#read the Ranged Weapons csv
ranged_file = "Resources/ranged.csv"
ranged_df=pd.read_csv(ranged_file)
ranged_df.head()

,agi,armor,classes,cooldown,critstrkrtng,dmg,dmgmax1,dmgmin1,dodgertng,dps,...,rgddmgmin,rgddps,rgdspeed,slotbak,socket1,socket2,speed,sta,str,versatility
0,NaN,NaN,NaN,0.000278,NaN,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,64.0,NaN,168.0,101.0,NaN,67.27,...,NaN,NaN,NaN,26.0,NaN,NaN,2.0,178.0,NaN,41.0
2,237.0,NaN,NaN,NaN,151.0,NaN,643.0,428.0,NaN,178.56,...,428.0,178.56,3.0,26.0,NaN,NaN,3.0,356.0,NaN,60.0
3,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,0.77,...,NaN,NaN,NaN,26.0,NaN,NaN,2.0,2.0,NaN,NaN
4,7.0,NaN,NaN,NaN,NaN,NaN,14.0,10.0,NaN,4.04,...,10.0,4.04,3.0,15.0,NaN,NaN,3.0,7.0,NaN,NaN

In [15]:
#Clean the data frame to have only relevant stats/columns
clean_ranged_df=ranged_df[["name_enus", "quality", "dmgmin1", "dmgmax1", "dps", "rgdspeed"]]
clean_ranged_df.head()
#Rename Columns
ranged_renamed=clean_ranged_df.rename(columns={"name_enus": "name",
                                       "quality": "quality",
                                       "dmgmin1": "min_damage",
                                      "dmgmax1": "max_damage",
                                      "dps": "dps",
                                      "rgdspeed": "weapon_speed_in_seconds"})
#drop NaN columns as these are not weapons and irrelevant to the dataset if they do not have a damage value
ranged_renamed=ranged_renamed.dropna(how='any')
ranged_renamed.head()

,name,quality,min_damage,max_damage,dps,weapon_speed_in_seconds
2,Bloodseeker,Epic,428.0,643.0,178.56,3.0
4,Farstrider's Longbow,Rare,10.0,14.0,4.04,3.0
5,Cry of the Wolf,Uncommon,3.0,7.0,1.77,3.0
9,Hand of Argus Crossfire,Uncommon,7.0,11.0,3.06,3.0
11,Hunting Bow,Uncommon,5.0,7.0,2.06,3.0

In [16]:
#Create Connection to PgAdmin
rds_connection_string = "postgres:postgres@localhost:5432/Warcraft Weapons"
engine = create_engine(f'postgresql://{rds_connection_string}')

#Verify table names
engine.table_names()

['onehand_weapons',
 'mh_weapons',
 'oh_weapons',
 'ranged_weapons',
 'twoh_weapons',
 'held_oh']

In [17]:
#Load Data Frames in SQL Database
ranged_renamed.to_sql(name='ranged_weapons', con=engine, if_exists='append', index=False)