# WoW One-Hand Weapons

In [4]:
import pandas as pd
from sqlalchemy import create_engine

In [5]:
#read the One-Hand Weapons csv
onehand_file = "Resources/One-Hand.csv"
onehand_df=pd.read_csv(onehand_file)
onehand_df.head()

,agi,agiint,agistr,agistrint,armor,classes,cooldown,corruption,critstrkrtng,dmg,...,rgdcritstrkrtng,slotbak,socket1,socket2,socket3,speed,splpwr,sta,str,versatility
0,118.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.0,NaN,...,NaN,13.0,NaN,NaN,NaN,2.6,NaN,178.0,NaN,46.0
1,118.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,13.0,NaN,NaN,NaN,1.8,NaN,178.0,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,13.0,NaN,NaN,NaN,2.6,NaN,NaN,3.0,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,13.0,NaN,NaN,NaN,2.6,NaN,178.0,NaN,75.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,13.0,NaN,NaN,NaN,2.6,NaN,178.0,118.0,36.0

In [6]:
#Clean the data frame to have only relevant stats/columns
clean_onehand_df=onehand_df[["name_enus", "quality", "dmgmin1", "dmgmax1", "dps", "mlespeed"]]
clean_onehand_df.head()
#Rename Columns
onehand_renamed=clean_onehand_df.rename(columns={"name_enus": "Name",
                                       "quality": "Quality",
                                       "dmgmin1": "Minumum Damage",
                                      "dmgmax1": "Maximum Damage",
                                      "dps": "Damage Per Second",
                                      "mlespeed": "Weapon Speed (in Seconds)"})
#drop NaN columns as these are not weapons and irrelevant to the dataset if they do not have a damage value
onehand_renamed=onehand_renamed.dropna(how='any')
onehand_renamed.head()

,Name,Quality,Minumum Damage,Maximum Damage,Damage Per Second,Weapon Speed (in Seconds)
0,Cold Forged Blade,Epic,262.0,438.0,134.77,2.6
1,The Lobotomizer,Epic,181.0,303.0,134.70,1.8
2,Stung,Uncommon,3.0,5.0,1.56,2.6
3,Cold Forged Hammer,Epic,153.0,197.0,67.36,2.6
4,Frostbite,Epic,227.0,473.0,134.76,2.6