# WoW Main Hand Items

In [59]:
import pandas as pd
from sqlalchemy import create_engine

In [60]:
#read the Main Hand Weapons csv
mh_file = "Resources/Main Hand.csv"
mh_df=pd.read_csv(mh_file)
mh_df.head()

,agi,armor,classes,cooldown,critstrkrtng,dmg,dmgmax1,dmgmin1,dps,dura,...,name_enus,nsockets,quality,reqlevel,slotbak,socket1,speed,sta,str,versatility
0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,0.61,30.0,...,Sunstrider Axe,NaN,Common,NaN,21.0,NaN,2.6,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,...,Coarse Sharpening Stone,NaN,Common,5.0,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,4.0,2.0,1.18,35.0,...,Lumberjack Axe,NaN,Common,4.0,21.0,NaN,2.6,NaN,NaN,NaN
3,NaN,NaN,NaN,0.000278,NaN,NaN,NaN,NaN,NaN,NaN,...,Minor Wizard Oil,NaN,Common,5.0,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,...,Coarse Weightstone,NaN,Common,5.0,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
#Clean the data frame to have only relevant stats/columns
clean_mh_df=mh_df[["name_enus", "quality", "dmgmin1", "dmgmax1", "dps","mlespeed"]]
clean_mh_df.head()
#Rename Columns
mh_renamed=clean_mh_df.rename(columns={"name_enus": "name",
                                       "quality": "quality",
                                       "dmgmin1": "min_damage",
                                      "dmgmax1": "max_damage",
                                      "dps": "dps",
                                      "mlespeed": "weapon_speed_in_seconds"})
mh_renamed
#drop NaN columns as these are not weapons and irrelevant to the dataset if they do not have a damage value
mh_renamed=mh_renamed.dropna(how='any')
mh_renamed.head()

,name,quality,min_damage,max_damage,dps,weapon_speed_in_seconds
0,Sunstrider Axe,Common,1.0,2.0,0.61,2.6
2,Lumberjack Axe,Common,2.0,4.0,1.18,2.6
5,Flanged Mace,Common,2.0,3.0,1.00,2.6
6,Kobold Excavation Pick,Common,1.0,3.0,0.89,2.6
7,Sunstrider Mace,Common,1.0,2.0,0.69,2.6

In [62]:
#Create Connection to PgAdmin
rds_connection_string = "postgres:postgres@localhost:5432/Warcraft Weapons"
engine = create_engine(f'postgresql://{rds_connection_string}')

#Verify table names
engine.table_names()

['onehand_weapons',
 'mh_weapons',
 'oh_weapons',
 'ranged_weapons',
 'twoh_weapons',
 'held_oh']

In [63]:
#Load Data Frames in SQL Database
mh_renamed.to_sql(name='mh_weapons', con=engine, if_exists='append', index=False)